"""Read/write mowers.toml and secrets.toml.

tomllib (stdlib) reads TOML but can't write it, and we don't want a new
dependency, so this module hand-rolls a minimal writer for our flat schemas.
Both files live beside app.py.

mowers.toml   — roster, safe to commit:
    [[mower]]
    name      = "Luba-XXXXXXXX"
    nickname  = "HV Luba"                       # optional, friendly app name
    hc33_host = "192.168.1.54"
    hc33_port = 9876
    iot_id    = "YOUR_IOT_ID"   # optional

secrets.toml  — Mammotion account creds, MUST stay out of git:
    email    = "you@example.com"
    password = "..."
"""

from __future__ import annotations

import os
import tomllib
from pathlib import Path

HERE = Path(__file__).parent
MOWERS_PATH = HERE / "mowers.toml"
SECRETS_PATH = HERE / "secrets.toml"


def _toml_quote(s: str) -> str:
    r"""Quote a string as a TOML basic string.

    Escapes backslash, double-quote, and control chars per the TOML spec so a
    password containing " or \ round-trips cleanly.
    """
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


# ── mowers.toml ──────────────────────────────────────────────────────────────
def load_mowers() -> list[dict]:
    """Parse mowers.toml into a normalized list.  Returns [] if the file is
    missing or has no entries (first-run / not-yet-onboarded)."""
    if not MOWERS_PATH.exists():
        return []
    with MOWERS_PATH.open("rb") as f:
        data = tomllib.load(f)
    out = []
    for m in data.get("mower", []):
        if "name" not in m or "hc33_host" not in m:
            continue  # skip malformed rows rather than crash the whole server
        out.append({
            "name":      m["name"],
            "nickname":  m.get("nickname") or None,
            "hc33_host": m["hc33_host"],
            "hc33_port": int(m.get("hc33_port", 9876)),
            "iot_id":    m.get("iot_id") or None,
        })
    return out


def save_mowers(mowers: list[dict]) -> None:
    """Write mowers.toml from a normalized list (atomic replace)."""
    lines = [
        "# HC33 mower roster — generated by the onboarding flow.",
        "# Safe to commit (no secrets).  Re-run onboarding or edit by hand.",
        "",
    ]
    for m in mowers:
        lines.append("[[mower]]")
        lines.append(f"name      = {_toml_quote(m['name'])}")
        if m.get("nickname"):
            lines.append(f"nickname  = {_toml_quote(m['nickname'])}")
        lines.append(f"hc33_host = {_toml_quote(m['hc33_host'])}")
        lines.append(f"hc33_port = {int(m.get('hc33_port', 9876))}")
        if m.get("iot_id"):
            lines.append(f"iot_id    = {_toml_quote(m['iot_id'])}")
        lines.append("")
    _atomic_write(MOWERS_PATH, "\n".join(lines))


# ── secrets.toml ─────────────────────────────────────────────────────────────
def load_secrets() -> tuple[str | None, str | None]:
    """Return (email, password).  secrets.toml wins; falls back to EMAIL /
    PASSWORD env vars so existing .env-based setups keep working."""
    email = password = None
    if SECRETS_PATH.exists():
        with SECRETS_PATH.open("rb") as f:
            data = tomllib.load(f)
        email = data.get("email")
        password = data.get("password")
    email = email or os.environ.get("EMAIL")
    password = password or os.environ.get("PASSWORD")
    return email, password


def save_secrets(email: str, password: str) -> None:
    """Write secrets.toml (atomic, mode 0600 where supported).

    Preserves any web_username / web_password already in the file so re-running
    onboarding doesn't wipe the web-UI login.
    """
    web_username = web_password = None
    if SECRETS_PATH.exists():
        with SECRETS_PATH.open("rb") as f:
            existing = tomllib.load(f)
        web_username = existing.get("web_username")
        web_password = existing.get("web_password")
    body = (
        "# Mammotion account credentials — DO NOT COMMIT.\n"
        "# Used for cloud login (camera) and ~monthly token refresh.\n"
        f"email    = {_toml_quote(email)}\n"
        f"password = {_toml_quote(password)}\n"
    )
    if web_username:
        body += f"web_username = {_toml_quote(web_username)}\n"
    if web_password:
        body += f"web_password = {_toml_quote(web_password)}\n"
    _atomic_write(SECRETS_PATH, body, mode=0o600)


def load_web_auth() -> tuple[str, str | None]:
    """Return (username, password) for the web-UI HTTP Basic gate.

    Resolution order: LUBA_WEB_USERNAME / LUBA_WEB_PASSWORD env vars win,
    otherwise the web_username / web_password keys in secrets.toml (gitignored).
    Username defaults to "luba".  A None/empty password means the gate is
    DISABLED and the server runs open — so an unconfigured install isn't locked
    out, but it logs a warning on startup.
    """
    username = os.environ.get("LUBA_WEB_USERNAME")
    password = os.environ.get("LUBA_WEB_PASSWORD")
    if (not username or not password) and SECRETS_PATH.exists():
        with SECRETS_PATH.open("rb") as f:
            data = tomllib.load(f)
        username = username or data.get("web_username")
        password = password or data.get("web_password")
    return (username or "luba"), (password or None)


def has_secrets() -> bool:
    email, password = load_secrets()
    return bool(email and password)


# ── internals ────────────────────────────────────────────────────────────────
def _atomic_write(path: Path, text: str, mode: int | None = None) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    if mode is not None:
        try:
            os.chmod(tmp, mode)
        except OSError:
            pass  # Windows / unsupported FS — best effort
    os.replace(tmp, path)  # atomic on the same filesystem
